{% set name = "pycompilation" %}
{% set version = "0.4.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pycompilation-{{ version }}.tar.gz
  sha256: fa8095aa956055b37de965d97bec0ba1a29d8b7354cc73bb4094d7286d8b883b
  patches:
    - importlib.patch

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  files:
    - on_the_fly_main.py
  requires:
    - {{ compiler('c') }}
    - cython
    - numpy
    - pip
    - python {{ python_min }}
  imports:
    - pycompilation
  commands:
    - pip check
    - python on_the_fly_main.py

about:
  home: https://github.com/bjodah/pycompilation
  summary: "pycompilation is a package for meta programming. It aims to support multiple compilers: GNU, Intel, PGI."
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moorepants
